# Generated by Django 3.0 on 2020-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
    ]
