# Generated by Django 3.0.6 on 2020-05-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0003_logincredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='EmpDetails',
        ),
    ]
