# Generated by Django 3.0.6 on 2020-05-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0004_auto_20200529_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('lid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facerecog.LoginCredentials')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
