# Generated by Django 3.0.6 on 2020-05-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facerecog.LoginCredentials'),
        ),
    ]
