# Generated by Django 3.0.6 on 2020-05-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0006_auto_20200530_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='lid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facerecog.LoginCredentials'),
        ),
    ]
